# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b3cad7972705f902e760083b1f88a4c51d59342ed144c81af4e403bf96f735bc90a5e06c6bbcacab38a92e790551e534df8158a8554f14391075881ef8ce9a35

test:
  secret_key_base: 2649cd164cc58af3d9bfced58acf6222bf88451bf8c470948482f3aa13cada69322b84a5dfaad20d980474abd3e3893cb116cf14bf15e7ab4dbe8f6c1bd65c6b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
